# Consumed by license_check.yml's Scancode action
# (zephyrproject-rtos/action_scancode) via its entrypoint.sh, which
# hardcodes reading this exact path. Schema: license_check.py in
# that action's repo. License keys follow ScanCode's own naming
# scheme, separate from SPDX — "bsd-new" is ScanCode's key for
# BSD-3-Clause.
license:
  main: bsd-new
  report_missing: true
  category: Permissive
copyright:
  check: true
exclude:
  extensions:
    - yml
    - yaml
    - html
    - rst
    - conf
    - cfg
    - toml
    - md
  langs:
    - HTML
