version = 1

[[annotations]]
path = [
    "**/*.cfg",
    "**/*.cmake",
    "**/*.conf",
    "**/*.json",
    "**/*.rst",
    "**/*.yaml",
    "**/*.yml",
    "**/*_defconfig",
    "**/CMakeLists.txt",
    "**/Kconfig*",
]
SPDX-License-Identifier = "BSD-3-Clause"
SPDX-FileCopyrightText = "Copyright (c) 2026 Texas Instruments Incorporated"
