#
# Copyright (c) 2026 Texas Instruments Incorporated
#
# SPDX-License-Identifier: BSD-3-Clause
#
# The projects list below is a hand-picked set of TI-relevant entries.
manifest:
  version: "1.2"
  defaults:
    remote: zephyrproject
  remotes:
  - name: zephyrproject
    url-base: https://github.com/zephyrproject-rtos
  - name: TexasInstruments
    url-base: https://github.com/TexasInstruments

  projects:
  - name: hal_ti
    remote: zephyrproject
    path: modules/hal/ti
    revision: 53c80140dd69905cc5e034f637eff9c66b2f9654
    groups:
    - hal
  - name: lvgl
    remote: TexasInstruments
    path: modules/lib/gui/lvgl
    revision: 96798d5cec1b4356e44a72d6900b5f29e861cc40
  - name: mcuboot
    remote: TexasInstruments
    path: bootloader/mcuboot
    revision: 96576b341ee19f1c3af6622256b0d4f3d408e1e3
  - name: zephyr
    remote: zephyrproject
    path: zephyr
    revision: c0bba90c366a395d2b55f3637aac066ecfb7757d
    import:
      name-allowlist:
      - mbedtls
      - cmsis
      - cmsis_6
      - libmetal
      - cmsis-dsp
      - cmsis-nn
      - liblc3
      - libsbc
      - open-amp
      - openthread
      - picolibc
      - zcbor
      - trusted-firmware-a
      - trusted-firmware-m
      - net-tools
      - fatfs
      - littlefs
  self:
    path: ti-zephyr
    west-commands: scripts/west-commands.yml
