# Copyright (c) 2026 Texas Instruments Incorporated
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_ADC=y
CONFIG_REGULATOR=y
CONFIG_REGULATOR_MSPM0_VREF=y
CONFIG_PWM=y
CONFIG_COUNTER=y
CONFIG_WATCHDOG=y
CONFIG_HWINFO=y
