# Copyright (c) 2026 Texas Instruments Incorporated
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_ADC=y
CONFIG_REGULATOR=y
CONFIG_RTC=y
CONFIG_AUXDISPLAY=y
CONFIG_HWINFO=y
CONFIG_HEAP_MEM_POOL_SIZE=256
