#
# Copyright (c) 2026 Texas Instruments Incorporated
# SPDX-License-Identifier: BSD-3-Clause
#

CONFIG_RTC=y
CONFIG_RTC_ALARM=y
CONFIG_RTC_UPDATE=y
CONFIG_RTC_CALIBRATION=y
CONFIG_RTC_TI_MSPM0_INTERVAL_TIMER=y
CONFIG_RTC_TI_MSPM0_PS_TIMER=y
